name = "aniket is so powerfull man in the wolrd"
print(name.upper())
print(name.lower())
print(name.replace("man" , "greatman"))
print(name.capitalize())
print(name.split(" "))
print(name.center(25)) # It makes space in the title 
print(name.count("aniket"))
print(name.startswith("a"))
print(name.endswith("d"))
print(len(name))
print(len(name),name.endswith("rd" ,39))
print(name.find("man"))
print(name.isalnum())
print(name.isalpha())
print(name.islower())
print(name.isprintable())
print(name.isspace())
print(name.istitle())
print(name.swapcase())